name: Mac OS Build
on:
  push:
jobs:
  build:
    name: Mac OS Build
    runs-on: macos-13
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.6

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.6

      - name: Setting DYLD_FALLBACK_LIBRARY_PATH
        run: echo "DYLD_FALLBACK_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64" >> $GITHUB_ENV

      - name: Verifying Haxe and Neko installation
        run: |
          haxe -version
          neko -version
          ls -l /Users/runner/hostedtoolcache/haxe/4.3.6/x64/
          ls -l /Users/runner/hostedtoolcache/neko/2.3.0/x64/

      - name: Print environment variables
        run: printenv

      - name: Installing/Updating libraries
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64
          haxe -cp ./update -D analyzer-optimize -main Update --interp
        shell: bash

      - name: Building the game
        run: |
          haxelib run lime build mac

      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Kade Engine Community
          path: export/release/macos/bin

      - name: Clearing already existing cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-macos") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@v4.0.2
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-macos
