name: Mac OS Build
on:
  push:
jobs:
  build:
    name: Mac OS Build
    runs-on: macos-13
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.6

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.4  # Utilizza Haxe 4.3.4
      - name: Setting up Neko manually
        run: |
          mkdir -p /usr/local/lib
          ln -sf /Users/runner/hostedtoolcache/neko/2.3.0/x64/libneko.2.dylib /usr/local/lib/libneko.2.dylib

      - name: Caching, Fixing Slow Compilation
        uses: actions/cache@v3
        with:
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-mac

      - name: Setting DYLD_LIBRARY_PATH
        run: echo "DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib" >> $GITHUB_ENV

      - name: Installing main libraries
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install hxcpp-debug-server
          haxelib install hxvlc
          haxelib install hscript
          haxelib install flixel-text-input
        
      - name: Setting up HaxeFlixel
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib run lime setup
          haxelib run lime setup flixel

      - name: Setting up Flixel Tools
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          echo "y" | haxelib run flixel-tools setup || echo "Flixel Tools setup failed"

      - name: Verifying Libraries
        run: |
          haxelib list

      - name: ENGINELibs1
        run: |
            haxelib git polymod https://github.com/swordcube/scriptless-polymod.git
            haxelib git tjson https://github.com/EliteMasterEric/TJSON.git
            haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved.git
            haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git --skip-dependencies

      - name: ENGINELibs2
        run: |
            haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel.git --skip-dependencies
            haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
            haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git

      - name: Building the game
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib run lime build mac || echo "Build failed"

      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Kade Engine Community
          path: export/release/macos/bin

      - name: Clearing already existing cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-macos") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Uploading new cache
        uses: actions/cache@v4.0.2
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-macos
