name: Mac OS Build
on:
  push:
jobs:
  build:
    name: Mac OS Build
    runs-on: macos-13
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.6
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.4
      - name: Setting up Neko manually
        run: |
          mkdir -p /usr/local/lib
          ln -sf /Users/runner/hostedtoolcache/neko/2.3.0/x64/libneko.2.dylib /usr/local/lib/libneko.2.dylib
      - name: Setting DYLD_LIBRARY_PATH
        run: echo "DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib" >> $GITHUB_ENV
      - name: Verifying Haxe and Neko installation
        run: |
          haxe -version
          neko -version
      - name: Installing Lime
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib install lime || echo "Lime installation failed"
      - name: Installing OpenFL
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib install openfl || echo "OpenFL installation failed"
      - name: Verify Lime and OpenFL installation
        run: |
          haxelib list
      - name: Installing/Updating libraries
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxe -cp ./update -D analyzer-optimize -main Update --interp || echo "Library update failed"
      - name: Building the game
        run: |
          export DYLD_LIBRARY_PATH=/Users/runner/hostedtoolcache/neko/2.3.0/x64:/usr/local/lib
          haxelib run lime build mac || echo "Build failed"
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Kade Engine Community
          path: export/release/macos/bin
