name: Mac OS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Mac OS Build
    runs-on: macos-13

    steps:
      # 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6

      # 2. Set up Haxe 4.3.4
      - name: Set up Haxe 4.3.4
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.4

      # 3. Cache Haxelib libraries
      - name: Restore Haxelib Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.haxelib
          key: macos-haxelib-cache-${{ runner.os }}-${{ hashFiles('haxe.json') }}
          restore-keys: |
            macos-haxelib-cache-${{ runner.os }}

      # 4. Install/Update libraries
      - name: Install or Update Libraries
        run: |
          haxe -cp ./update -D analyzer-optimize -main Update --interp --verbose
        shell: bash
        timeout-minutes: 10

      # 5. Build the game
      - name: Build the Game
        run: |
          haxelib run lime build mac --verbose
        timeout-minutes: 20

      # 6. Upload build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Kade Engine Community Build
          path: export/release/macos/bin
          retention-days: 5

      # 7. Clear existing cache (if needed)
      - name: Clear Cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key.startsWith("macos-haxelib-cache-")) {
                console.log('Clearing ' + cache.key + '...');
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
                console.log("Cache cleared.");
              }
            }

      # 8. Upload new cache
      - name: Upload New Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.haxelib
          key: macos-haxelib-cache-${{ runner.os }}-${{ hashFiles('haxe.json') }}
          restore-keys: |
            macos-haxelib-cache-${{ runner.os }}
